//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mil.Paperwork.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResidualValueReportStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResidualValueReportStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mil.Paperwork.Domain.Resources.ResidualValueReportStrings", typeof(ResidualValueReportStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ке.
        /// </summary>
        internal static string CoeffExploitation {
            get {
                return ResourceManager.GetString("CoeffExploitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значення коефіцієнтів, які використовуються під час визначення сукупного крефіцієнта зносу.
        /// </summary>
        internal static string CoefficientsMergedColumnTitle {
            get {
                return ResourceManager.GetString("CoefficientsMergedColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ктс.
        /// </summary>
        internal static string CoeffTechState {
            get {
                return ResourceManager.GetString("CoeffTechState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кр.
        /// </summary>
        internal static string CoeffWork {
            get {
                return ResourceManager.GetString("CoeffWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кзб.
        /// </summary>
        internal static string CoeffZB {
            get {
                return ResourceManager.GetString("CoeffZB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Залишкова вартість (графа 7 х графу 10 х графу 4)
        ///(Взал).
        /// </summary>
        internal static string ResidualValueColumnTitle {
            get {
                return ResourceManager.GetString("ResidualValueColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сукупний коефіцієнт зносу
        ///(Кскз).
        /// </summary>
        internal static string TotalWearCoefficientColumnTitle {
            get {
                return ResourceManager.GetString("TotalWearCoefficientColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посилання
        ///на звіт про оцінку майна.
        /// </summary>
        internal static string ValuationReportReferenceColumnTitle {
            get {
                return ResourceManager.GetString("ValuationReportReferenceColumnTitle", resourceCulture);
            }
        }
    }
}
