name: Manual CD 

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Channel'
        required: true
        type: choice
        options:
          - Debug
          - Release
      targetPlatform:
        description: 'Target Platform'
        required: true
        type: choice
        options:
          - x86
          - x64
      tag:
        description: 'Tag'
        required: false
        type: string

jobs:
  call_common_code:
    uses: ./.github/workflows/cd_common.yml
    with:
      channel: ${{ inputs.channel }}
      targetPlatform: ${{ inputs.targetPlatform }}
      tagName: ${{ inputs.tag && inputs.tag != '' && format('$env:branchName.{0}.{1}.{2}', inputs.tag, inputs.channel, inputs.targetPlatform) || format('$env:branchName.{0}.{1}', inputs.channel, inputs.targetPlatform) }}
      tag: ${{ inputs.tag }}
      
    secrets:
      Base64_Encoded_Pfx: ${{ secrets.Base64_Encoded_Pfx }}
      Pfx_Key: ${{ secrets.Pfx_Key }}
